# Generated by Django 3.2.7 on 2022-07-22 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showimg', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='展示图片')),
                ('name', models.CharField(max_length=1024, verbose_name='名称')),
                ('intro', models.CharField(max_length=1024, verbose_name='介绍')),
                ('area', models.CharField(max_length=1024, verbose_name='地区')),
                ('author', models.CharField(max_length=1024, verbose_name='作者')),
                ('chubanshe', models.CharField(max_length=1024, verbose_name='出版社')),
                ('status', models.CharField(default='0', max_length=1024, verbose_name='目前状态')),
                ('show_time', models.IntegerField(default=0, verbose_name='观看次数')),
                ('age', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('shou_count', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '宠物信息',
                'verbose_name_plural': '宠物信息',
            },
        ),
        migrations.CreateModel(
            name='PetsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='分类名称')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Zan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.petsinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
            },
        ),
        migrations.AddField(
            model_name='petsinfo',
            name='atype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.petstype', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='petsinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024, verbose_name='评论内容')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('petsInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.petsinfo')),
                ('pre_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pets.commentinfo', verbose_name='父评论id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.petsinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
            },
        ),
    ]
