# Generated by Django 3.2.7 on 2022-07-25 09:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20220725_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsinfo',
            name='intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='introduce'),
        ),
    ]
