# Generated by Django 5.0.1 on 2025-03-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0003_alter_petsinfo_intro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adoption",
            name="status",
            field=models.CharField(
                choices=[("0", "registered"), ("1", "passed"), ("2", "adopted")],
                default="0",
                max_length=1024,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="petsinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "release"),
                    ("1", "adopted person selected"),
                    ("2", "adopted"),
                ],
                default="0",
                max_length=1024,
                verbose_name="status",
            ),
        ),
    ]
