# Generated by Django 3.2.7 on 2022-07-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id'], 'verbose_name': 'user manage', 'verbose_name_plural': 'user manage'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mpassword',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='mpassword'),
        ),
    ]
